[package]
name = "pass-generator-app"
version = "0.1.0"
edition = "2024"

[dependencies]
gdk-pixbuf = "0.21.5"
glib = "0.21.5"
gtk4 = "0.10.3"
rand = "0.9.2"

[build-dependencies]
winresource = "0.1.28"
